# opencode user config. The live config, ~/.config/opencode/opencode.json, is
# GENERATED by `nx-opencode-ollama-sync` -- it is deliberately not managed here
# and is a real file, not a symlink. Two things feed it:
#
#   opencode.base.json      shared, hand-written settings (mcp, default_agent,
#                           skills). Symlinked out-of-store below so it can be
#                           edited without a nix rebuild.
#   the local ollama store  the installed model set, which differs per host and
#                           changes on every pull/rm, so it is derived rather
#                           than hand-maintained in a file shared across hosts.
#
# The merge happens in the sync script rather than through opencode's own config
# layering (global -> OPENCODE_CONFIG -> project) because that layering only
# works in a terminal: it needs OPENCODE_CONFIG in the environment, and
# GUI-launched clients import only a fixed allowlist of variables from a login
# shell. T3 Code's allowlist, for one, is PATH / SSH_AUTH_SOCK / HOMEBREW_* /
# XDG_* / locale / display -- so OPENCODE_CONFIG is dropped and the opencode
# server it spawns never sees the ollama block. Writing one merged file means
# every client sees the same models regardless of how it was launched.
#
# Also managed here: tui.json (TUI plugins) and plugins/ (TUI slot plugins, e.g.
# the session-id resume-line). commands/ and skills/ in ~/.config/opencode are
# symlinks maintained by repos/raiz/agent-config, and auth/state live in
# ~/.local/share/opencode (secrets, never in this repo).
{ config, lib, pkgs, ... }:

let
  opencodeOllamaSync = pkgs.writeShellApplication {
    name = "nx-opencode-ollama-sync";
    runtimeInputs = [ pkgs.python3 ];
    text = ''
      exec python3 ${../scripts/opencode-ollama-models.py} "$@"
    '';
  };
in
{
  home.packages = [ opencodeOllamaSync ];

  # Input to the generator, never the live config.
  xdg.configFile."opencode/opencode.base.json".source =
    config.lib.file.mkOutOfStoreSymlink
      "${config.home.homeDirectory}/repos/nixos/home/shared/opencode/opencode.base.json";

  # Regenerate on every switch so base edits and a `git pull` land without a
  # manual step, and so a fresh host gets a config at all. Rerun by hand after
  # `ollama pull` / `ollama rm`, which a rebuild does not cover.
  #
  # Ordered after linkGeneration (itself entryAfter writeBoundary, so that
  # boundary alone is not enough): the base symlink above has to exist before
  # the script reads it, and on the first switch after this change the stale
  # opencode.json symlink has to be gone before the script writes a real file
  # over it. A failure here warns rather than aborting the whole activation --
  # the script already exits 0 when ollama is simply unreachable.
  home.activation.opencodeOllamaSync =
    lib.hm.dag.entryAfter [ "linkGeneration" ] ''
      $DRY_RUN_CMD ${opencodeOllamaSync}/bin/nx-opencode-ollama-sync \
        || echo "warning: nx-opencode-ollama-sync failed; ~/.config/opencode/opencode.json not refreshed" >&2
    '';

  # TUI config: declares TUI-only plugins (kept out of the opencode config so
  # the server plugin pass never tries to load a tui-only module).
  xdg.configFile."opencode/tui.json".source =
    config.lib.file.mkOutOfStoreSymlink
      "${config.home.homeDirectory}/repos/nixos/home/shared/opencode/tui.json";

  # TUI slot plugins (loaded via the `plugin` array in tui.json).
  xdg.configFile."opencode/plugins".source =
    config.lib.file.mkOutOfStoreSymlink
      "${config.home.homeDirectory}/repos/nixos/home/shared/opencode/plugins";
}
