#!/usr/bin/env python3
"""Generate opencode's ollama provider block from the local ollama store.

The set of installed models is host-specific and changes whenever you pull or
remove one, so it is derived here rather than hand-maintained in
home/shared/opencode/opencode.json (which is shared across hosts). Output goes
to a file pointed at by OPENCODE_CONFIG, which opencode merges over the global
config -- see home/shared/opencode.nix.

Run after any `ollama pull` / `ollama rm`:

    nx-opencode-ollama-sync            # write ~/.config/opencode/ollama.local.json
    nx-opencode-ollama-sync --print    # dump to stdout instead
    nx-opencode-ollama-sync --max-ctx 65536

Context is capped per engine, because the two allocate KV cache differently:

  ggml (gguf)      pre-allocates the whole window at load. A 27B at the
                   advertised 262144 reserves ~17 GB of KV cache before the
                   first token, which is what OOMs the Metal backend -- see
                   the comment in hosts/mac/configuration.nix. Capped hard.

  MLX (safetensors) allocates lazily as the sequence grows, so num_ctx is a
                   ceiling rather than a reservation. Measured on a 64 GB M5
                   Pro: qwen3.6:35b-a3b-nvfp4 completed a real 227k-token
                   prompt with no OOM. Costs nothing to set high.

The MLX cap is deliberately below the models' native 262144 anyway, because
opencode uses limit.context to decide when to compact, and throughput falls
off at the top of the window (measured, same model: 87.8 tok/s generation and
1328 tok/s prefill on a short context, versus 26.5 and 635 at ~227k -- a 6
minute prefill). 128k stays clear of that cliff while being far larger than
any single turn.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request

DEFAULT_HOST = os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434")
DEFAULT_OUT = os.path.join(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")),
    "opencode",
    "ollama.local.json",
)
DEFAULT_MAX_CTX_GGML = 32768
DEFAULT_MAX_CTX_MLX = 131072
DEFAULT_MAX_OUTPUT = 8192


def api(host: str, path: str, payload: dict | None = None) -> dict:
    url = f"{host.rstrip('/')}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url, data=data, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def context_length(model_info: dict) -> int | None:
    """Pull `<arch>.context_length` without needing to know the architecture."""
    for key, value in model_info.items():
        if key.endswith(".context_length") and isinstance(value, int):
            return value
    return None


def engine_of(info: dict) -> str:
    """safetensors is how ollama ships the MLX-native quants; gguf runs ggml."""
    details = info.get("details") or {}
    return "MLX" if details.get("format") == "safetensors" else "ggml"


def describe(tag: str, info: dict, engine: str) -> str:
    details = info.get("details") or {}
    size = details.get("parameter_size") or "?"
    quant = details.get("quantization_level") or "?"
    return f"{tag} — {size} {quant} ({engine})"


def build(host: str, max_ctx_ggml: int, max_ctx_mlx: int, max_output: int) -> dict:
    tags = api(host, "/api/tags").get("models") or []
    models: dict[str, dict] = {}

    for entry in sorted(tags, key=lambda m: m.get("name", "")):
        tag = entry.get("name")
        if not tag:
            continue
        try:
            info = api(host, "/api/show", {"model": tag})
        except urllib.error.URLError as exc:
            print(f"warning: skipping {tag}: {exc}", file=sys.stderr)
            continue

        caps = info.get("capabilities") or []
        if "completion" not in caps:
            continue  # embedding-only models are not chat providers

        engine = engine_of(info)
        cap = max_ctx_mlx if engine == "MLX" else max_ctx_ggml
        native_ctx = context_length(info.get("model_info") or {})
        ctx = min(native_ctx, cap) if native_ctx else cap

        models[tag] = {
            "name": describe(tag, info, engine),
            "tools": "tools" in caps,
            "reasoning": "thinking" in caps,
            "attachment": "vision" in caps,
            "options": {"num_ctx": ctx},
            "limit": {"context": ctx, "output": max_output},
        }

    return {
        "$schema": "https://opencode.ai/config.json",
        "//": (
            "GENERATED by nx-opencode-ollama-sync from the local ollama store. "
            "Do not edit; rerun after `ollama pull` / `ollama rm`. "
            "Shared, hand-written opencode settings live in "
            "home/shared/opencode/opencode.json."
        ),
        "provider": {
            "ollama": {
                "name": "Ollama (local)",
                "npm": "ollama-ai-provider-v2",
                "options": {"baseURL": f"{host.rstrip('/')}/api"},
                "models": models,
            }
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=DEFAULT_HOST, help="ollama base URL")
    parser.add_argument("--out", default=DEFAULT_OUT, help="output path")
    parser.add_argument(
        "--max-ctx-ggml",
        type=int,
        default=DEFAULT_MAX_CTX_GGML,
        help="context cap for gguf models (ggml pre-allocates KV cache)",
    )
    parser.add_argument(
        "--max-ctx-mlx",
        type=int,
        default=DEFAULT_MAX_CTX_MLX,
        help="context cap for MLX models (lazy KV allocation)",
    )
    parser.add_argument("--max-output", type=int, default=DEFAULT_MAX_OUTPUT)
    parser.add_argument(
        "--print", dest="to_stdout", action="store_true", help="print instead of write"
    )
    args = parser.parse_args()

    try:
        config = build(args.host, args.max_ctx_ggml, args.max_ctx_mlx, args.max_output)
    except urllib.error.URLError as exc:
        print(f"error: cannot reach ollama at {args.host}: {exc}", file=sys.stderr)
        return 1

    rendered = json.dumps(config, indent=2, ensure_ascii=False) + "\n"

    if args.to_stdout:
        sys.stdout.write(rendered)
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as handle:
        handle.write(rendered)

    count = len(config["provider"]["ollama"]["models"])
    print(f"wrote {count} model(s) to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
