#!/usr/bin/env python3
"""Generate ~/.config/opencode/opencode.json from shared settings + local ollama.

The live opencode config is generated rather than checked in, because it has two
sources that cannot live in one file:

  opencode.base.json      shared, hand-written settings (mcp, default_agent,
                          skills), tracked in this repo and identical on every
                          host.
  the local ollama store  the installed model set, which is host-specific and
                          changes whenever you pull or remove a model.

Merging them here rather than layering them through opencode's own config chain
(global -> OPENCODE_CONFIG -> project) is deliberate: that chain needs
OPENCODE_CONFIG in the environment, which GUI-launched clients do not have --
see the comment in home/shared/opencode.nix. One merged file is what every
client, terminal or GUI, actually reads.

Runs on every home-manager activation. Rerun by hand after `ollama pull` /
`ollama rm`:

    nx-opencode-ollama-sync            # write ~/.config/opencode/opencode.json
    nx-opencode-ollama-sync --print    # dump to stdout instead
    nx-opencode-ollama-sync --max-ctx-mlx 65536

If ollama is unreachable the base settings are still written, without a provider
block, so a host with ollama stopped (or never installed) keeps working mcp and
skills config. A missing or malformed base is a hard error instead -- writing a
config without it would silently drop those settings.

Context is capped per engine, because the two allocate KV cache differently:

  ggml (gguf)      pre-allocates the whole window at load. A 27B at the
                   advertised 262144 reserves ~17 GB of KV cache before the
                   first token, which is what OOMs the Metal backend -- see
                   the comment in hosts/mac/configuration.nix. Capped hard.

  MLX (safetensors) allocates lazily as the sequence grows, so num_ctx is a
                   ceiling rather than a reservation. Measured on a 64 GB M5
                   Pro: qwen3.6:35b-a3b-nvfp4 completed a real 227k-token
                   prompt with no OOM. Costs nothing to set high.

The MLX cap is deliberately below the models' native 262144 anyway, because
opencode uses limit.context to decide when to compact, and throughput falls
off at the top of the window (measured, same model: 87.8 tok/s generation and
1328 tok/s prefill on a short context, versus 26.5 and 635 at ~227k -- a 6
minute prefill). 128k stays clear of that cliff while being far larger than
any single turn.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request

DEFAULT_HOST = os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434")
CONFIG_DIR = os.path.join(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")),
    "opencode",
)
DEFAULT_BASE = os.path.join(CONFIG_DIR, "opencode.base.json")
DEFAULT_OUT = os.path.join(CONFIG_DIR, "opencode.json")
DEFAULT_MAX_CTX_GGML = 32768
DEFAULT_MAX_CTX_MLX = 131072
DEFAULT_MAX_OUTPUT = 8192

SCHEMA_URL = "https://opencode.ai/config.json"
GENERATED_NOTE = (
    "GENERATED by nx-opencode-ollama-sync -- do not edit. Shared settings live "
    "in home/shared/opencode/opencode.base.json (symlinked to "
    "~/.config/opencode/opencode.base.json); the provider block below is read "
    "from the local ollama store. Rerun after editing the base or after "
    "`ollama pull` / `ollama rm`."
)


def api(host: str, path: str, payload: dict | None = None) -> dict:
    url = f"{host.rstrip('/')}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url, data=data, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def context_length(model_info: dict) -> int | None:
    """Pull `<arch>.context_length` without needing to know the architecture."""
    for key, value in model_info.items():
        if key.endswith(".context_length") and isinstance(value, int):
            return value
    return None


def engine_of(info: dict) -> str:
    """safetensors is how ollama ships the MLX-native quants; gguf runs ggml."""
    details = info.get("details") or {}
    return "MLX" if details.get("format") == "safetensors" else "ggml"


def describe(tag: str, info: dict, engine: str) -> str:
    details = info.get("details") or {}
    size = details.get("parameter_size") or "?"
    quant = details.get("quantization_level") or "?"
    return f"{tag} — {size} {quant} ({engine})"


def load_base(path: str) -> dict:
    """The shared settings. Absent or broken is fatal -- see module docstring."""
    try:
        with open(path) as handle:
            base = json.load(handle)
    except FileNotFoundError:
        raise SystemExit(f"error: base config not found: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"error: base config {path} is not valid JSON: {exc}")

    if not isinstance(base, dict):
        raise SystemExit(f"error: base config {path} is not a JSON object")
    return base


def deep_merge(base: dict, overlay: dict) -> dict:
    """Recursive merge; overlay wins, so a `provider` key in the base survives."""
    merged = dict(base)
    for key, value in overlay.items():
        current = merged.get(key)
        if isinstance(current, dict) and isinstance(value, dict):
            merged[key] = deep_merge(current, value)
        else:
            merged[key] = value
    return merged


def ollama_provider(
    host: str, max_ctx_ggml: int, max_ctx_mlx: int, max_output: int
) -> dict:
    """The provider overlay, or {} if ollama has nothing to offer right now."""
    try:
        tags = api(host, "/api/tags").get("models") or []
    except urllib.error.URLError as exc:
        print(f"warning: cannot reach ollama at {host}: {exc}", file=sys.stderr)
        print("warning: writing config without a provider block", file=sys.stderr)
        return {}

    models: dict[str, dict] = {}

    for entry in sorted(tags, key=lambda m: m.get("name", "")):
        tag = entry.get("name")
        if not tag:
            continue
        try:
            info = api(host, "/api/show", {"model": tag})
        except urllib.error.URLError as exc:
            print(f"warning: skipping {tag}: {exc}", file=sys.stderr)
            continue

        caps = info.get("capabilities") or []
        if "completion" not in caps:
            continue  # embedding-only models are not chat providers

        engine = engine_of(info)
        cap = max_ctx_mlx if engine == "MLX" else max_ctx_ggml
        native_ctx = context_length(info.get("model_info") or {})
        ctx = min(native_ctx, cap) if native_ctx else cap

        models[tag] = {
            "name": describe(tag, info, engine),
            "tools": "tools" in caps,
            "reasoning": "thinking" in caps,
            "attachment": "vision" in caps,
            "options": {"num_ctx": ctx},
            "limit": {"context": ctx, "output": max_output},
        }

    if not models:
        return {}

    return {
        "provider": {
            "ollama": {
                "name": "Ollama (local)",
                "npm": "ollama-ai-provider-v2",
                "options": {"baseURL": f"{host.rstrip('/')}/api"},
                "models": models,
            }
        }
    }


def build(
    base: dict, host: str, max_ctx_ggml: int, max_ctx_mlx: int, max_output: int
) -> dict:
    overlay = ollama_provider(host, max_ctx_ggml, max_ctx_mlx, max_output)

    # $schema and the generated-file note go first so a reader hits the warning
    # before the settings; everything else keeps the base's own key order.
    config = {
        "$schema": base.get("$schema", SCHEMA_URL),
        "//": GENERATED_NOTE,
    }
    rest = {key: value for key, value in base.items() if key != "$schema"}
    config.update(deep_merge(rest, overlay))
    return config


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=DEFAULT_HOST, help="ollama base URL")
    parser.add_argument("--base", default=DEFAULT_BASE, help="shared settings path")
    parser.add_argument("--out", default=DEFAULT_OUT, help="output path")
    parser.add_argument(
        "--max-ctx-ggml",
        type=int,
        default=DEFAULT_MAX_CTX_GGML,
        help="context cap for gguf models (ggml pre-allocates KV cache)",
    )
    parser.add_argument(
        "--max-ctx-mlx",
        type=int,
        default=DEFAULT_MAX_CTX_MLX,
        help="context cap for MLX models (lazy KV allocation)",
    )
    parser.add_argument("--max-output", type=int, default=DEFAULT_MAX_OUTPUT)
    parser.add_argument(
        "--print", dest="to_stdout", action="store_true", help="print instead of write"
    )
    args = parser.parse_args()

    config = build(
        load_base(args.base),
        args.host,
        args.max_ctx_ggml,
        args.max_ctx_mlx,
        args.max_output,
    )

    rendered = json.dumps(config, indent=2, ensure_ascii=False) + "\n"

    if args.to_stdout:
        sys.stdout.write(rendered)
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as handle:
        handle.write(rendered)

    provider = (config.get("provider") or {}).get("ollama") or {}
    count = len(provider.get("models") or {})
    print(f"wrote {args.out} ({count} ollama model(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
